language: bash
sudo: required
script:
- upv/github-travis/upv_bootstrap_travis.sh
# push first, to speed up next build, even if it fails
- ./upv.sh upv/github-travis docker-hub/push
# download and prepare the source data
- ./upv.sh . dpp "run ./download" && ./upv.sh . dpp "run ./join-meetings"
# build into dist/ directory
- ./upv.sh upv/static-files build
# create the dist package
- ./upv.sh . dist_package
