COMMITTEE_DETAIL_URL = "committees/{committee_id}.html"
MEETING_URL = "meetings/{}/{}/{}.html"
MEMBER_URL = "members/{member_id}.html"
COMMITTEE_LIST_KNESSET_URL = "committees/knesset-{num}.html"
COMMITTEES_INDEX_URL = "committees/index.html"
